### ISSUE TITLE
S50/S5 Support?

### ISSUE THREAD

**Issue by exetico** [TheRealMoeder/TheRealMoeder.github.io#1]
Hey,

Are they also working for the S50? :-)

**Comment by TheRealMoeder** [comment]
Yes, they should. If you experience any issues, please tell me.

**Comment by dennisdegreef** [comment]
Could you include the example WAVs with this? :)
As in, being able to hear what a soundpack sounds like before having to install

**Comment by exetico** [comment]
I ended up making a custom danish pack - but thanks for the answer :-)!
