### ISSUE TITLE
Roborock Zuzana

### ISSUE THREAD

**Issue by pilotak** [TheRealMoeder/TheRealMoeder.github.io#2]
Hi i wanted to use a `30-rockrobo-voicepack_Zusana_Zuzana.pkg` but it only has 77 bytes - it doesn't have any sounds included, would it be possible to fix it?

**Comment by TheRealMoeder** [comment]
There was a bug, thanks for noticing (Zuzana was coded as "Zusana" internally...). I regenerated your voice pack with ID39:
https://therealmoeder.github.io/39-rockrobo-voicepack_Zuzana_Zuzana_Rebuild_forID30.pkg
